version: "3"
services:
  node-img-1:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:3000"
    volumes:
      - ./src:/app/src:ro
    environment:
      - REACT_APP_NAME=Development
